//---------------------------------------------------------------------------

#include <vcl.h>
#pragma hdrstop

#include "mainform.h"
#include "fakeio.h"
#include "var_form.h"
//---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"
TMainFrm *MainFrm;
//---------------------------------------------------------------------------
#define pi 3.1415926535897932384626433832795f
//---------------------------------------------------------------------------
__fastcall TMainFrm::TMainFrm(TComponent* Owner)
	: TForm(Owner)
{
	//da.SetZoomFactor(8400000);
	da.SetZoomFactor(10000);

	vessel.heading = 40.0f;
	vessel.position.lat = 51.9364818f;
	vessel.position.lon = 4.5162849f;
	vessel.speed = 0;

	AddLocations();

	da.SetCenterLoc(start.loc);

	VarForm = new TVarForm(Application);
	VarForm->Show();


	main_init();
}
//---------------------------------------------------------------------------
void __fastcall TMainFrm::AddRefLocations()
{
	TDrawPoint zero,utrecht,amsterdam,rotterdam;

	// zero loc
	zero.clr = clBlack;
	zero.loc.lat = 0;
	zero.loc.lon = 0;
	da.AddDrawPoint(zero);
	// Utrecht
	utrecht.clr = clYellow;
	utrecht.loc.lat = 52.0906949f;
	utrecht.loc.lon = 5.1220616f;
	da.AddDrawPoint(utrecht);
	// Amsterdam
	amsterdam.clr = clRed;
	amsterdam.loc.lat = 52.3788516f;
	amsterdam.loc.lon = 4.9004368f;
	da.AddDrawPoint(amsterdam);
	// Rotterdam
	rotterdam.clr = clGreen;
	rotterdam.loc.lat = 51.9290846f;
	rotterdam.loc.lon = 4.4931016f;
	da.AddDrawPoint(rotterdam);

	// Kralingse plas
	TDrawPoint kp1, kp2, kp3,kp4;
	// kp1  kp2
	// kp3  kp4
	kp1.clr = clBlue;
	kp2.clr = clBlue;
	kp3.clr = clBlue;
	kp4.clr = clBlue;
	kp1.loc.lat = 51.9413472f;
	kp1.loc.lon = 4.513745f;
	kp2.loc.lat = 51.9380235f;
	kp2.loc.lon = 4.5250358f;
	kp3.loc.lat = 51.9340276f;
	kp3.loc.lon = 4.5056552f;
	kp4.loc.lat = 51.9281928f;
	kp4.loc.lon = 4.5183095f;
	da.AddDrawPoint(kp1);
	da.AddDrawPoint(kp2);
	da.AddDrawPoint(kp3);
	da.AddDrawPoint(kp4);
}
//---------------------------------------------------------------------------
void __fastcall TMainFrm::AddLocations()
{
	AddRefLocations();

	// startpunt navigatie: ergens midden in de Kralingse plas
	start.clr = clWhite;
	start.loc.lat = 51.9364818f;
	start.loc.lon = 4.5162849f;
	da.AddDrawPoint(start);
	// eindpunt/finish navigatie: wat verder weg (voor de tuin)
	finish.clr = clWhite;
	finish.loc.lat = 51.932278f;
	finish.loc.lon = 4.521163f;
	da.AddDrawPoint(finish);

	gp_start.lat = start.loc.lat;
	gp_start.lon = start.loc.lon;
	gp_finish.lat = finish.loc.lat;
	gp_finish.lon = finish.loc.lon;

}
//---------------------------------------------------------------------------
float __fastcall TMainFrm::Pwm2MotorFact(int dc)
{
	if (!dc)
		return 0.0f;
	else
		return (dc-3000)/1000.0f;
}
//---------------------------------------------------------------------------
UnicodeString MainStateToText(TMainState s)
{
	switch (s) {
	case msManualMode: return L"msManualMode";
	case msAutoMode: return L"msAutoMode";
	case msCountJoyUp: return L"msCountJoyUp";
	case msConfirmGotoPosX: return L"msConfirmGotoPosX";
	case msCountJoyDown: return L"msCountJoyDown";
	case msConfirmSavePosX: return L"msConfirmSavePosX";
	case msCountJoyUpRetn: return L"msCountJoyUpRetn";
	case msCountJoyDownRetn: return L"msCountJoyDownRetn";
	case msCmdError: return L"msCmdError";
	default:
		return L"???";
	}
}
//---------------------------------------------------------------------------
void __fastcall TMainFrm::Timer1Timer(TObject *Sender)
{
	global_ms_timer += Timer1->Interval;

	if (CbRemoteCtrlOn->Checked) {
		pd5_pulse_duration=SbMotorV->Position;
		pd6_pulse_duration=SbMotorH->Position;
		pd3_pulse_duration=4000 - (SbPos->Position - 2000);
		pb3_pulse_duration=SbManAuto->Position;
	} else {
		// If the remote is off, no servo waveform is
		// generated by the receiver. So zeroes.
		pd6_pulse_duration=0;
		pd5_pulse_duration=0;
		pd3_pulse_duration=0;
		pb3_pulse_duration=0;
	}

	// run atmel program
	SendVesselPosToAtmel();
	process();

	if (prog_op.Length()) {
		if (ListBox1->Items->Count > 5)
			ListBox1->Clear();

		ListBox1->Items->Add(prog_op);
		prog_op="";
	}

	if (PORTB & _BV(PORTB5))
		ShLed->Brush->Color=clRed;
	else
		ShLed->Brush->Color=clBlack;

	vessel.bearing_sp = bearing_sp;

	float avr_motor_l(0),avr_motor_r(0);

	avr_motor_l = Pwm2MotorFact(OCR1A);
	avr_motor_r = Pwm2MotorFact(OCR1B);

	vessel.motor_left = avr_motor_l -(SbMotorL->Position / 100.0);
	vessel.motor_right = avr_motor_r -(SbMotorR->Position / 100.0);

	vessel_path.push_back(vessel.position);

	vessel.CalcSpeedAndHeading();
	vessel.Move(Timer1->Interval);
	//vessel.heading += 0.2;

	da.SetScreenDims(PaintBox1->Width,PaintBox1->Height);

	da.RenderTo(PaintBox1->Canvas,vessel,vessel_path);


	VarForm->ClearLines();

	VarForm->AddLine(L"vessel.motor_left = " + FormatFloat(L"0.00",vessel.motor_left));
	VarForm->AddLine(L"vessel.motor_right = " + FormatFloat(L"0.00",vessel.motor_right));
	VarForm->AddLine(L"---");
	VarForm->AddLine(L"gp_mem_1 = " + gp_mem_1.ToString());
	VarForm->AddLine(L"gp_mem_2 = " + gp_mem_2.ToString());
	VarForm->AddLine(L"gp_mem_3 = " + gp_mem_3.ToString());
	VarForm->AddLine(L"---");
	VarForm->AddLine(L"gp_current = " + gp_current.ToString());
	VarForm->AddLine(L"---");
	VarForm->AddLine(L"main_state = " + MainStateToText(main_state));
	VarForm->AddLine(L"---");
	VarForm->AddLine(L"pd3 pd = " + FloatToStr(pd3_pulse_duration));
	VarForm->AddLine(L"pb3 pd = " + FloatToStr(pb3_pulse_duration));
	VarForm->AddLine(L"pd5 pd = " + FloatToStr(pd5_pulse_duration));
	VarForm->AddLine(L"pd6 pd = " + FloatToStr(pd6_pulse_duration));

	VarForm->AddLine(L"---");

	VarForm->Update();


}
//---------------------------------------------------------------------------
void __fastcall TMainFrm::SendVesselPosToAtmel()
{
	TGpsLoc loc = vessel.position;
//	loc.lat = -89.0;
//	loc.lon = -179.0;

	bool bValidity = CbValidGps->Checked;

	// Convert current location to a GPS string parseable by
	// the TinyGPS library.
	UnicodeString sRMC = loc.GetGPRMC(vessel.heading,bValidity);

	// Send as fake UART message
	for (int i(1);i<=sRMC.Length();++i) {
		Fake_UART_ISR(sRMC[i]);
		process();
	}
}
//---------------------------------------------------------------------------

void __fastcall TMainFrm::OnZoomFactKeyDown(TObject *Sender, WORD &Key, TShiftState Shift)

{
	if (Key==VK_RETURN) {
		da.SetZoomFactor(EdZoomFactor->Text.ToDouble());
	}
}
//---------------------------------------------------------------------------

void __fastcall TMainFrm::BtnZeroClick(TObject *Sender)
{
	SbMotorL->Position=0;
	SbMotorR->Position=0;
}
//---------------------------------------------------------------------------

